// GENERATED by @edgedb/generate v0.3.3

import * as $ from "../../reflection.ts";
import * as _ from "../../imports.ts";
import type * as _default from "../default.ts";
import type * as _common from "../common.ts";
import type * as _std from "../std.ts";
import type * as _inventory from "./inventory.ts";
export type $SaleOrderλShape = $.typeutil.flatten<_default.$DatedTypeλShape & _common.$HasCompanyOwnerPrivateλShape & {
  "sale_order_lines": $.LinkDesc<$SaleOrderLine, $.Cardinality.Many, {}, false, false,  false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
}>;
type $SaleOrder = $.ObjectType<"b2c::sales::SaleOrder", $SaleOrderλShape, null, [
  ..._default.$DatedType['__exclusives__'],
  ..._common.$HasCompanyOwnerPrivate['__exclusives__'],
]>;
const $SaleOrder = $.makeType<$SaleOrder>(_.spec, "c3282178-36fe-11ee-beb8-e5cd4b0f5d52", _.syntax.literal);

const SaleOrder: $.$expr_PathNode<$.TypeSet<$SaleOrder, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SaleOrder, $.Cardinality.Many), null);

export type $SaleOrderLineλShape = $.typeutil.flatten<_default.$DatedTypeλShape & _common.$HasCompanyOwnerPrivateλShape & {
  "product": $.LinkDesc<_inventory.$Product, $.Cardinality.AtMostOne, {}, false, false,  false, false>;
  "discount": $.PropertyDesc<_std.$float64, $.Cardinality.AtMostOne, false, false, false, false>;
  "price": $.PropertyDesc<_std.$float64, $.Cardinality.AtMostOne, false, false, false, false>;
  "qty": $.PropertyDesc<_std.$float64, $.Cardinality.AtMostOne, false, false, false, false>;
  "subtotal": $.PropertyDesc<_std.$float64, $.Cardinality.AtMostOne, false, true, false, false>;
  "name": $.PropertyDesc<_std.$str, $.Cardinality.AtMostOne, false, false, false, false>;
  "<sale_order_lines[is b2c::sales::SaleOrder]": $.LinkDesc<$SaleOrder, $.Cardinality.Many, {}, false, false,  false, false>;
  "<sale_order_lines": $.LinkDesc<$.ObjectType, $.Cardinality.Many, {}, false, false,  false, false>;
}>;
type $SaleOrderLine = $.ObjectType<"b2c::sales::SaleOrderLine", $SaleOrderLineλShape, null, [
  ..._default.$DatedType['__exclusives__'],
  ..._common.$HasCompanyOwnerPrivate['__exclusives__'],
]>;
const $SaleOrderLine = $.makeType<$SaleOrderLine>(_.spec, "c31b34fe-36fe-11ee-bec0-c31a35d20121", _.syntax.literal);

const SaleOrderLine: $.$expr_PathNode<$.TypeSet<$SaleOrderLine, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($SaleOrderLine, $.Cardinality.Many), null);



export { $SaleOrder, SaleOrder, $SaleOrderLine, SaleOrderLine };

type __defaultExports = {
  "SaleOrder": typeof SaleOrder;
  "SaleOrderLine": typeof SaleOrderLine
};
const __defaultExports: __defaultExports = {
  "SaleOrder": SaleOrder,
  "SaleOrderLine": SaleOrderLine
};
export default __defaultExports;
