// GENERATED by @edgedb/generate v0.3.3

import * as $ from "../reflection.ts";
import * as _ from "../imports.ts";
import _module__account from "./api/account.ts";
import _module__product from "./api/product.ts";


type __defaultExports = {
  "account": typeof _module__account;
  "product": typeof _module__product
};
const __defaultExports: __defaultExports = {
  "account": _module__account,
  "product": _module__product
};
export default __defaultExports;
