// GENERATED by @edgedb/generate v0.3.3

import * as $ from "../reflection.ts";
import * as _ from "../imports.ts";
import _module__inventory from "./b2c/inventory.ts";
import _module__sales from "./b2c/sales.ts";


type __defaultExports = {
  "inventory": typeof _module__inventory;
  "sales": typeof _module__sales
};
const __defaultExports: __defaultExports = {
  "inventory": _module__inventory,
  "sales": _module__sales
};
export default __defaultExports;
