// GENERATED by @edgedb/generate v0.3.3

import * as $ from "../reflection.ts";
import * as _ from "../imports.ts";
import _module__api_usage from "./client/api_usage.ts";
import _module__invoices from "./client/invoices.ts";
import _module__orders from "./client/orders.ts";


type __defaultExports = {
  "api_usage": typeof _module__api_usage;
  "invoices": typeof _module__invoices;
  "orders": typeof _module__orders
};
const __defaultExports: __defaultExports = {
  "api_usage": _module__api_usage,
  "invoices": _module__invoices,
  "orders": _module__orders
};
export default __defaultExports;
