// GENERATED by @edgedb/generate v0.3.3

import * as $ from "../reflection.ts";
import * as _ from "../imports.ts";
import type * as _std from "./std.ts";
import type * as _default from "./default.ts";
export type $AdminRoleHasFullAccessAccessPolicyλShape = $.typeutil.flatten<_std.$Object_07d9fd2227fb11ee8ad3435ff4e00f5fλShape & {
}>;
type $AdminRoleHasFullAccessAccessPolicy = $.ObjectType<"common::AdminRoleHasFullAccessAccessPolicy", $AdminRoleHasFullAccessAccessPolicyλShape, null, [
  ..._std.$Object_07d9fd2227fb11ee8ad3435ff4e00f5f['__exclusives__'],
]>;
const $AdminRoleHasFullAccessAccessPolicy = $.makeType<$AdminRoleHasFullAccessAccessPolicy>(_.spec, "783609f6-3699-11ee-b726-a9ec20e83d45", _.syntax.literal);

const AdminRoleHasFullAccessAccessPolicy: $.$expr_PathNode<$.TypeSet<$AdminRoleHasFullAccessAccessPolicy, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($AdminRoleHasFullAccessAccessPolicy, $.Cardinality.Many), null);

export type $HasCompanyOwnerPrivateλShape = $.typeutil.flatten<_std.$Object_07d9fd2227fb11ee8ad3435ff4e00f5fλShape & {
  "owner": $.LinkDesc<_default.$Company, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $HasCompanyOwnerPrivate = $.ObjectType<"common::HasCompanyOwnerPrivate", $HasCompanyOwnerPrivateλShape, null, [
  ..._std.$Object_07d9fd2227fb11ee8ad3435ff4e00f5f['__exclusives__'],
]>;
const $HasCompanyOwnerPrivate = $.makeType<$HasCompanyOwnerPrivate>(_.spec, "7ebb77fc-3699-11ee-9d4f-e5d8d1327806", _.syntax.literal);

const HasCompanyOwnerPrivate: $.$expr_PathNode<$.TypeSet<$HasCompanyOwnerPrivate, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($HasCompanyOwnerPrivate, $.Cardinality.Many), null);

export type $HasCompanyOwnerλShape = $.typeutil.flatten<_std.$Object_07d9fd2227fb11ee8ad3435ff4e00f5fλShape & {
  "owner": $.LinkDesc<_default.$Company, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $HasCompanyOwner = $.ObjectType<"common::HasCompanyOwner", $HasCompanyOwnerλShape, null, [
  ..._std.$Object_07d9fd2227fb11ee8ad3435ff4e00f5f['__exclusives__'],
]>;
const $HasCompanyOwner = $.makeType<$HasCompanyOwner>(_.spec, "7847491e-3699-11ee-9bc1-d747466bef54", _.syntax.literal);

const HasCompanyOwner: $.$expr_PathNode<$.TypeSet<$HasCompanyOwner, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($HasCompanyOwner, $.Cardinality.Many), null);

export type $HasUserOwnerPrivateλShape = $.typeutil.flatten<_std.$Object_07d9fd2227fb11ee8ad3435ff4e00f5fλShape & {
  "owner": $.LinkDesc<_default.$User, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $HasUserOwnerPrivate = $.ObjectType<"common::HasUserOwnerPrivate", $HasUserOwnerPrivateλShape, null, [
  ..._std.$Object_07d9fd2227fb11ee8ad3435ff4e00f5f['__exclusives__'],
]>;
const $HasUserOwnerPrivate = $.makeType<$HasUserOwnerPrivate>(_.spec, "82aaf78e-3699-11ee-b46d-b93f986551ee", _.syntax.literal);

const HasUserOwnerPrivate: $.$expr_PathNode<$.TypeSet<$HasUserOwnerPrivate, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($HasUserOwnerPrivate, $.Cardinality.Many), null);

export type $HasUserOwnerλShape = $.typeutil.flatten<_std.$Object_07d9fd2227fb11ee8ad3435ff4e00f5fλShape & {
  "owner": $.LinkDesc<_default.$User, $.Cardinality.One, {}, false, false,  false, false>;
}>;
type $HasUserOwner = $.ObjectType<"common::HasUserOwner", $HasUserOwnerλShape, null, [
  ..._std.$Object_07d9fd2227fb11ee8ad3435ff4e00f5f['__exclusives__'],
]>;
const $HasUserOwner = $.makeType<$HasUserOwner>(_.spec, "7850dc86-3699-11ee-b3e2-9bddb65bef9c", _.syntax.literal);

const HasUserOwner: $.$expr_PathNode<$.TypeSet<$HasUserOwner, $.Cardinality.Many>, null> = _.syntax.$PathNode($.$toSet($HasUserOwner, $.Cardinality.Many), null);



export { $AdminRoleHasFullAccessAccessPolicy, AdminRoleHasFullAccessAccessPolicy, $HasCompanyOwnerPrivate, HasCompanyOwnerPrivate, $HasCompanyOwner, HasCompanyOwner, $HasUserOwnerPrivate, HasUserOwnerPrivate, $HasUserOwner, HasUserOwner };

type __defaultExports = {
  "AdminRoleHasFullAccessAccessPolicy": typeof AdminRoleHasFullAccessAccessPolicy;
  "HasCompanyOwnerPrivate": typeof HasCompanyOwnerPrivate;
  "HasCompanyOwner": typeof HasCompanyOwner;
  "HasUserOwnerPrivate": typeof HasUserOwnerPrivate;
  "HasUserOwner": typeof HasUserOwner
};
const __defaultExports: __defaultExports = {
  "AdminRoleHasFullAccessAccessPolicy": AdminRoleHasFullAccessAccessPolicy,
  "HasCompanyOwnerPrivate": HasCompanyOwnerPrivate,
  "HasCompanyOwner": HasCompanyOwner,
  "HasUserOwnerPrivate": HasUserOwnerPrivate,
  "HasUserOwner": HasUserOwner
};
export default __defaultExports;
